name: ProjectsV2 scheduler
description: Schedules items in Projects V2 based on Schedule field.
inputs:
  token:
    description: Github Personal AccessToken (PAT) with full project scope.
    required: true

  project:
    description: |-
      Project URL. For user projects use "users/{username}/projects/{number}"
      and for orgs use "orgs/{name}/projects/{number}".
    required: true

  schedule-field-name:
    description: Name of a TEXT field that stores the scheduled date.
    required: false
    default: 'Schedule'

  status-field-name:
    description: Name of the status field.
    required: false
    default: 'Status'

  schedule-state-name:
    description: Schedule state name. In order to schedule an issue you have to chage it's state to this name.
    required: false
    default: 'Schedule'

  todo-state-name:
    description: Todo state name. When schedule time turns from a future to the past the item will have it's state changed to the specified one.
    required: false
    default: 'Todo'

outputs:
  de-scheduled-count:
    description: The count of issues that were de-scheduled (moved back to TODO column)

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      env:
        ACTION_PATH: ${{ github.action_path }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const action_path = process.env.ACTION_PATH
          const script = require(`${action_path}/action.js`)
          await script({github, context, core})